### ISSUE TITLE
Change member function naming to snake_case

### ISSUE THREAD

**Issue by AndyZe** [PickNikRobotics/Universal_Robots_ROS2_Driver#13]
Per the conversation [here](https://github.com/ros-controls/ros2_control/issues/269).

Let's change the member function names to be snake_case rather than camelCase. I would do it in a new PR

**Comment by nbbrooks** [comment]
Check on style guides for ROS2 and greater community - is there a common style being used?

**Comment by nbbrooks** [comment]
Passing snake case linter.
