### ISSUE TITLE
prepare URDFs and launch files for other robot types

### ISSUE THREAD

**Issue by nbbrooks** [PickNikRobotics/Universal_Robots_ROS2_Driver#27]

**Comment by livanov93** [comment]
#14 addressed most of the stuff. There is only need to add other urxy_moveit_packages if we plan to have them here. For now we have all configuration files, launch and urdfs together with moveit configuration files for ur5 and ur5_e

**Comment by nbbrooks** [comment]
Also depends on https://github.com/PickNikRobotics/Universal_Robots_ROS2_Driver/issues/47
