### ISSUE TITLE
Correct "Move to home bug" #50 properly

### ISSUE THREAD

**Issue by destogl** [PickNikRobotics/Universal_Robots_ROS2_Driver#67]
This is just a quick fix for preventing unwanted behavior of the real robot at startup. The real fix will come in a later pull request.

_Originally posted by @MGBla in https://github.com/PickNikRobotics/Universal_Robots_ROS2_Driver/issues/63#issuecomment-815847005_

**Comment by destogl** [comment]
Set joint_states to "nan" if robot state is unknown.

**Comment by MGBla** [comment]
This was merged in #92
